export enum CONSTANTS {
  PORT_ODESSA = "portOdessa",
  COPART_CONSTANTS = "copartConstant",
  CITIES_FOR_DELIVERY = "citiesForDelivery",
  IAAI_CONSTANT = "IAAIConstant",
  HAZMAT_CONST = "HAZMATConst",
  SUV = "SUV",
  COPART_FINAL_BET_RANGE = "CopartFinalBetRange",
  IAAI_FINAL_BET_RANGE = "IAAIFinalBetRange",
  COPART_BETS_IN_REAL_TIME = "CopartBetsInRealTime",
  IAAI_BETS_IN_REAL_TIME = "IAAIBetsInRealTime",
  COPART_CITIES_AND_PORTS = "CopartCitiesAndPorts",
  IAAI_CITIES_AND_PORTS = "IAAICitiesAndPorts",
  INSURANCE_CONST = "insuranceConst",
}
